name: mitiquiz
description: A Quiz for Symbolism and Myths.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # Mobx (flutter packages pub run build_runner watch --delete-conflicting-outputs)
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  # Service locator
  get_it: ^3.1.0
  # UI
  bubble_bottom_bar: ^1.2.0
  simple_animations: ^1.3.3
  url_launcher: ^5.4.2
  material_design_icons_flutter: ^4.0.5245
  cupertino_icons: ^0.1.2
  # Value equality
  equatable: ^1.0.1
  # Functional programming thingies
  dartz: ^0.8.9
  # Remote API
  dio: ^3.0.9
  http: ^0.12.0+3
  data_connection_checker: ^0.3.4
  # Local cache
  hive: ^1.4.1+1
  # For OS-specific directory paths
  path_provider: ^1.3.0
  # Formatting
  diacritic: ^0.1.1
  intl: ^0.16.1

dev_dependencies:
  build_runner: ^1.8.1
  mobx_codegen: ^1.0.3
  flutter_launcher_icons: ^0.7.4
  flutter_launcher_name: ^0.0.1

  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_launcher_name:
  name: "Mitiquiz"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - google_fonts/